# Generated by Django 6.0.1 on 2026-02-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_product_alter_student_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productColor',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='proudctStatus',
            field=models.BooleanField(default=True),
        ),
    ]
