# Generated by Django 6.0.1 on 2026-02-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_product_productcolor_product_proudctstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('showTime', models.CharField(max_length=20)),
                ('ticketPrice', models.PositiveIntegerField()),
                ('MovieStory', models.TextField()),
            ],
            options={
                'db_table': 'Movies',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='productDescription',
            field=models.TextField(),
        ),
    ]
